export const SOURCES = {
  collabnb: { label: 'Collabnb', hue: 'teal' },
  instagram: { label: 'Instagram', hue: 'pink' },
  casting: { label: 'Casting', hue: 'amber' },
  reddit: { label: 'Reddit', hue: 'orange' },
  x: { label: 'X', hue: 'slate' },
  form: { label: 'Form', hue: 'violet' },
  link: { label: 'Link', hue: 'sky' },
};

export const STAGES = ['found', 'drafted', 'approved', 'sent', 'replied', 'booked'];

export const STAGE_LABEL = {
  found: 'Found',
  drafted: 'Drafted',
  approved: 'Approved',
  sent: 'Sent',
  replied: 'Replied',
  booked: 'Booked',
  skipped: 'Skipped',
};

export const DEFAULT_PROFILE = {
  name: '',
  handle: '',
  followers: '',
  engagement: '',
  basedIn: '',
  niches: 'travel, hotels, lifestyle',
  formats: 'Reels, TikToks, photo sets',
  pastWork: '',
  rate: '',
  portfolio: '',
  voiceSamples: '',
  banned: 'elevate, unlock, stunning, breathtaking, vibrant, seamless, game-changer, journey, delve, passionate about, dream collab, hope this finds you well',
};

// Fictional sample briefs so the MVP has something to show. Real sources plug in later.
export const SAMPLE_POOL = [
  {
    source: 'collabnb',
    brand: 'Sample · Casa Alba',
    title: '3-night stay for Reels + stills',
    location: 'Lisbon, Portugal',
    dates: 'Nov 4 – Nov 20',
    comp: 'Free stay + €300',
    deliverables: ['2 Reels', '10 edited stills', '3 Stories'],
    requirements: 'Travel or design niche, 10K+ followers',
    tags: ['travel', 'hotels', 'design'],
    channel: 'collabnb',
  },
  {
    source: 'instagram',
    brand: 'Sample · @salt.and.stone',
    title: '"Looking for UGC creators" post',
    location: 'Remote',
    dates: 'Rolling',
    comp: '$150–$250 per video',
    deliverables: ['1 UGC video (30s)'],
    requirements: 'Skincare or lifestyle, any size',
    tags: ['lifestyle', 'beauty', 'ugc'],
    channel: 'dm',
  },
  {
    source: 'casting',
    brand: 'Sample · Harbour Resort Group',
    title: 'Resort travel influencer campaign',
    location: 'Queensland, Australia',
    dates: 'Dec 1 – Dec 6',
    comp: 'Flights + stay + fee',
    deliverables: ['3 Reels', '1 TikTok', 'Raw footage'],
    requirements: 'Travel niche, 25K+ followers, AU based preferred',
    tags: ['travel', 'resort', 'lifestyle'],
    channel: 'form',
  },
  {
    source: 'reddit',
    brand: 'Sample · r/UGCcreators',
    title: 'Coffee brand needs 5 creators this month',
    location: 'Remote',
    dates: 'Due Oct 30',
    comp: '$100 + product',
    deliverables: ['1 unboxing video'],
    requirements: 'Food or lifestyle',
    tags: ['food', 'lifestyle', 'ugc'],
    channel: 'dm',
  },
  {
    source: 'x',
    brand: 'Sample · @wanderdesk',
    title: 'Co-working hotel launch — creators wanted',
    location: 'Bali, Indonesia',
    dates: 'Jan 10 – Jan 17',
    comp: 'Free stay (7 nights)',
    deliverables: ['1 Reel', '1 YouTube short', 'Blog post'],
    requirements: 'Remote-work or travel creators',
    tags: ['travel', 'hotels', 'remote work'],
    channel: 'dm',
  },
  {
    source: 'form',
    brand: 'Sample · Tidewater Surf Co.',
    title: 'Ambassador application (Google Form)',
    location: 'Anywhere coastal',
    dates: 'Applications close Oct 15',
    comp: 'Gear + 15% affiliate',
    deliverables: ['2 posts / month'],
    requirements: 'Outdoor, surf, travel',
    tags: ['outdoor', 'travel', 'lifestyle'],
    channel: 'form',
  },
];
