// ─── Mock creator profile (matches @collabnb_creator_profile_v1 shape) ──────────
export const MOCK_CREATOR = {
  id: 'mock-benjamin',
  full_name: 'Benjamin',
  username: 'ben.venturing',
  email: 'benventuring@gmail.com',
  role: 'creator',
  tier: 'Micro Influencer',
  bio: 'Travel & lifestyle creator documenting unique stays and hidden gems around the world. Passionate about authentic content that inspires people to explore.',
  avatar_url: 'https://ucarecdn.com/6d425040-e4c3-46f0-a774-91ac597ebe24/-/format/auto/',
  follower_count: 413500,
  engagement_rate: 8.2,
  collab_count: 47,
  instagram_handle: 'ben.venturing',
  tiktok_handle: 'ben.venturing',
  youtube_handle: 'ben.venturing',
  portfolio: 'beacons.ai/benventuring',
  is_founder: true,
  beta: true,
  city: 'Asheville',
  region: 'NC',
};

// ─── Sample listings (Unsplash photos, for Explore + Past Collabs) ────────────
export const SAMPLE_LISTINGS = [
  {
    id: '1',
    title: 'Glacier Prime Cabin',
    subtitle: 'Rustic cabin in old-growth forest',
    location: 'Lake Tahoe, CA',
    host_name: 'Sarah Mitchell',
    host_verified: true,
    image: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=80',
    rating: 4.97,
    review_count: 84,
    compensation: 'Free Stay · 3 nights',
    deliverables: '3 Reels, 5 Photos',
    deliverable_load: 'Moderate',
    collab_type: 'UGC Video',
    dates_available: 'Feb–Apr 2026',
    property_type: 'Cabin',
    is_featured: true,
  },
  {
    id: '2',
    title: 'Tranquil Waterfront Retreat',
    subtitle: 'Cliffside villa with private infinity pool',
    location: 'Malibu, CA',
    host_name: 'David Chen',
    host_verified: true,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    rating: 4.93,
    review_count: 112,
    compensation: 'Free Stay · 2 nights',
    deliverables: '2 Reels, 8 Photos',
    deliverable_load: 'Moderate',
    collab_type: 'Instagram Reels',
    dates_available: 'Jan–Mar 2026',
    property_type: 'Villa',
    is_featured: true,
  },
  {
    id: '3',
    title: 'Desert Oasis Villa',
    subtitle: 'Modernist retreat surrounded by Joshua trees',
    location: 'Joshua Tree, CA',
    host_name: 'Emma Rodriguez',
    host_verified: false,
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
    rating: 4.88,
    review_count: 57,
    compensation: 'Free Stay · 2 nights',
    deliverables: '4 Reels, 10 Photos',
    deliverable_load: 'Heavy',
    collab_type: 'TikTok',
    dates_available: 'Mar–May 2026',
    property_type: 'Villa',
    is_featured: false,
  },
  {
    id: '4',
    title: 'Mountain Lodge Escape',
    subtitle: 'Slope-side luxury with panoramic views',
    location: 'Aspen, CO',
    host_name: 'Michael Park',
    host_verified: true,
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    rating: 4.95,
    review_count: 203,
    compensation: 'Free Stay · 3 nights + $500',
    deliverables: '5 Reels, 12 Photos',
    deliverable_load: 'Heavy',
    collab_type: 'YouTube Vlog',
    dates_available: 'Dec 2025–Feb 2026',
    property_type: 'Lodge',
    is_featured: true,
  },
  {
    id: '5',
    title: 'Lakeside Forest Treehouse',
    subtitle: 'Elevated treehouse above a private lake',
    location: 'Asheville, NC',
    host_name: 'Rachel Torres',
    host_verified: true,
    image: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800&q=80',
    rating: 4.99,
    review_count: 41,
    compensation: 'Free Stay · 2 nights',
    deliverables: '2 Reels, 6 Photos',
    deliverable_load: 'Light',
    collab_type: 'Photography',
    dates_available: 'Apr–Jun 2026',
    property_type: 'Treehouse',
    is_featured: false,
  },
  {
    id: '6',
    title: 'Desert Dome Glamping',
    subtitle: 'Geodesic dome under the Milky Way',
    location: 'Sedona, AZ',
    host_name: 'James Okafor',
    host_verified: false,
    image: 'https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=800&q=80',
    rating: 4.91,
    review_count: 78,
    compensation: 'Free Stay · 1 night',
    deliverables: '1 Reel, 4 Photos',
    deliverable_load: 'Light',
    collab_type: 'Instagram Reels',
    dates_available: 'Year-round',
    property_type: 'Glamping',
    is_featured: false,
  },
  {
    id: '7',
    title: 'Vineyard Wine Estate',
    subtitle: 'Private villa on a working estate',
    location: 'Napa Valley, CA',
    host_name: 'Sophie Laurent',
    host_verified: true,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
    rating: 4.96,
    review_count: 129,
    compensation: 'Free Stay · 2 nights + tasting',
    deliverables: '3 Reels, 8 Photos',
    deliverable_load: 'Moderate',
    collab_type: 'Full Package',
    dates_available: 'Mar–Nov 2026',
    property_type: 'Estate',
    is_featured: true,
  },
  {
    id: '8',
    title: 'Smoky Mountain Retreat',
    subtitle: 'Secluded cabin above the clouds',
    location: 'Gatlinburg, TN',
    host_name: 'Anna Whitfield',
    host_verified: true,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    rating: 4.94,
    review_count: 63,
    compensation: 'Free Stay · 2 nights',
    deliverables: '2 Reels, 6 Photos',
    deliverable_load: 'Light',
    collab_type: 'UGC Video',
    dates_available: 'Apr–Oct 2026',
    property_type: 'Cabin',
    is_featured: false,
  },
  {
    id: '9',
    title: 'Charleston Harbor Cottage',
    subtitle: 'Historic cottage steps from the waterfront',
    location: 'Charleston, SC',
    host_name: 'Marcus Bell',
    host_verified: true,
    image: 'https://images.unsplash.com/photo-1559599101-f09722fb4948?w=800&q=80',
    rating: 4.90,
    review_count: 88,
    compensation: 'Free Stay · 3 nights',
    deliverables: '3 Reels, 10 Photos',
    deliverable_load: 'Moderate',
    collab_type: 'Blog Post',
    dates_available: 'Year-round',
    property_type: 'Cottage',
    is_featured: false,
  },
];

// ─── Sample collaborations (matches @collabnb_applications_v1 shape) ──────────
export const SAMPLE_COLLABORATIONS = [
  {
    id: 1,
    listing_id: '1',
    property_name: 'Glacier Prime Cabin',
    location: 'Lake Tahoe, CA',
    host_name: 'Sarah Mitchell',
    image: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=80',
    status: 'pending',
    status_text: 'Pending Upload',
    dates: 'Feb 15–18, 2026',
    deliverables: '3 Reels, 5 Photos',
    days_left: 12,
    is_active: true,
  },
  {
    id: 2,
    listing_id: '2',
    property_name: 'Tranquil Waterfront Retreat',
    location: 'Malibu, CA',
    host_name: 'David Chen',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    status: 'uploaded',
    status_text: 'Uploaded & Tagged (AI)',
    dates: 'Jan 28–31, 2026',
    deliverables: '2 Reels, 8 Photos',
    days_left: null,
    is_active: true,
  },
  {
    id: 3,
    listing_id: '3',
    property_name: 'Desert Oasis Villa',
    location: 'Joshua Tree, CA',
    host_name: 'Emma Rodriguez',
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
    status: 'approved',
    status_text: 'Approved · Payment Released',
    dates: 'Jan 10–13, 2026',
    deliverables: '4 Reels, 10 Photos',
    days_left: null,
    payment: '$850',
    is_active: false,
  },
];

// ─── Sample inbox threads ─────────────────────────────────────────────────────
export const SAMPLE_THREADS = [
  {
    id: 't1',
    listing_title: 'Glacier Prime Cabin',
    host_name: 'Sarah Mitchell',
    host_avatar: null,
    tag: 'Collab',
    last_message: 'Looking forward to the shoot next week!',
    timestamp: 'Apr 19',
    unread: 0,
    is_founder: true,
  },
  {
    id: 't2',
    listing_title: 'Mountain Lodge Escape',
    host_name: 'Michael Park',
    host_avatar: null,
    tag: 'Application',
    last_message: "Hi! I'd love to collaborate on this property...",
    timestamp: 'Apr 18',
    unread: 1,
    is_founder: false,
  },
  {
    id: 't3',
    listing_title: 'Desert Oasis Villa',
    host_name: 'Emma Rodriguez',
    host_avatar: null,
    tag: 'Pitch',
    last_message: 'I have some ideas for unique content angles...',
    timestamp: 'Apr 17',
    unread: 3,
    is_founder: false,
  },
];
