export const DESTINATIONS = [
  { label: 'Asheville, NC',   icon: 'mountain', desc: 'Mountains & Blue Ridge', coords: [35.60, -82.55] },
  { label: 'Lake Tahoe, CA',  icon: 'lake',     desc: 'Alpine lake & forest',   coords: [39.10, -120.03] },
  { label: 'Malibu, CA',      icon: 'beach',    desc: 'Cliffside & beachfront', coords: [34.03, -118.78] },
  { label: 'Joshua Tree, CA', icon: 'desert',   desc: 'Desert & stargazing',    coords: [34.13, -116.31] },
  { label: 'Aspen, CO',       icon: 'snow',     desc: 'Mountain luxury',        coords: [39.19, -106.82] },
  { label: 'Sedona, AZ',      icon: 'canyon',   desc: 'Red rocks & glamping',   coords: [34.87, -111.76] },
  { label: 'Napa Valley, CA', icon: 'wine',     desc: 'Wine country estates',   coords: [38.50, -122.27] },
  { label: 'Gatlinburg, TN',  icon: 'forest',   desc: 'Smoky Mountains',        coords: [35.71, -83.51] },
  { label: 'Charleston, SC',  icon: 'harbour',  desc: 'Historic harbour',       coords: [32.78, -79.93] },
];

// Curated set of major countries for the "Where" search — lets someone type a
// country (not just a US state/region) and get a recognized match even before
// we have real listings there. Extend this list as new markets open up.
export const COUNTRIES = [
  { name: 'United States', aliases: ['usa', 'us', 'america'] },
  { name: 'Canada' },
  { name: 'Mexico' },
  { name: 'United Kingdom', aliases: ['uk', 'britain', 'england'] },
  { name: 'France' },
  { name: 'Germany' },
  { name: 'Italy' },
  { name: 'Spain' },
  { name: 'Portugal' },
  { name: 'Netherlands' },
  { name: 'Switzerland' },
  { name: 'Austria' },
  { name: 'Greece' },
  { name: 'Croatia' },
  { name: 'Iceland' },
  { name: 'Ireland' },
  { name: 'Norway' },
  { name: 'Sweden' },
  { name: 'Denmark' },
  { name: 'Finland' },
  { name: 'Poland' },
  { name: 'Czech Republic' },
  { name: 'Turkey' },
  { name: 'Cyprus' },
  { name: 'Morocco' },
  { name: 'Egypt' },
  { name: 'South Africa' },
  { name: 'Kenya' },
  { name: 'Tanzania' },
  { name: 'United Arab Emirates', aliases: ['uae', 'dubai'] },
  { name: 'Saudi Arabia' },
  { name: 'Israel' },
  { name: 'Jordan' },
  { name: 'India' },
  { name: 'Thailand' },
  { name: 'Vietnam' },
  { name: 'Indonesia', aliases: ['bali'] },
  { name: 'Philippines' },
  { name: 'Malaysia' },
  { name: 'Singapore' },
  { name: 'Japan' },
  { name: 'South Korea' },
  { name: 'China' },
  { name: 'Australia' },
  { name: 'New Zealand' },
  { name: 'Fiji' },
  { name: 'Brazil' },
  { name: 'Argentina' },
  { name: 'Chile' },
  { name: 'Peru' },
  { name: 'Costa Rica' },
];

export const COLLAB_TYPES = [
  { label: 'UGC Video',       emoji: '🎬' },
  { label: 'Instagram Reels', emoji: '📸' },
  { label: 'TikTok',          emoji: '🎵' },
  { label: 'Photography',     emoji: '📷' },
  { label: 'YouTube Vlog',    emoji: '▶️' },
  { label: 'Blog Post',       emoji: '✍️' },
  { label: 'Full Package',    emoji: '✦' },
];

export const AVAIL_OPTIONS = [
  'Any time',
  'This month',
  'Next month',
  'Next 3 months',
  'Next 6 months',
];
